namespace TeamsIntegration.Api.Models.Requests;

/// <summary>Creates a database mapping between a Teams channel and its workflow webhook.</summary>
public sealed record CreateWebhookUrlRequest
{
    /// <summary>Microsoft Teams team identifier. Graph identifiers are strings, not GUIDs.</summary>
    public required string TeamId { get; init; }
    /// <summary>Microsoft Teams channel identifier, commonly ending in <c>@thread.tacv2</c>.</summary>
    public required string ChannelId { get; init; }
    /// <summary>Absolute HTTPS URL generated by Microsoft Teams Workflows.</summary>
    public required string Url { get; init; }
}
