namespace TeamsIntegration.Api.Models.Requests;

/// <summary>Replacement values for an existing channel webhook assignment.</summary>
public sealed record UpdateWebhookUrlRequest
{
    /// <summary>Microsoft Teams team identifier.</summary>
    public required string TeamId { get; init; }
    /// <summary>Microsoft Teams channel identifier.</summary>
    public required string ChannelId { get; init; }
    /// <summary>Absolute HTTPS URL generated by Microsoft Teams Workflows.</summary>
    public required string Url { get; init; }
}
