// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamsIntegration.Api.Data;

#nullable disable

namespace TeamsIntegration.Api.Migrations
{
    [DbContext(typeof(TeamsDbContext))]
    [Migration("20260814133805_AddWebhookUrlEntity")]
    partial class AddWebhookUrlEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamsIntegration.Api.Entities.MessageMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<string>("ETag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("e_tag");

                    b.Property<string>("GraphHostedContentId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("graph_hosted_content_id");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("object_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TeamsMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("BucketName", "ObjectName")
                        .IsUnique()
                        .HasDatabaseName("ux_bucket_name_object_name");

                    b.HasIndex("TeamsMessageId", "GraphHostedContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_message_media_hosted_content");

                    b.ToTable("message_media", (string)null);
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.TeamsMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("channel_id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("graph_message_id");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<DateTimeOffset?>("MessageCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_created_at");

                    b.Property<DateTimeOffset?>("MessageDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_deleted_at");

                    b.Property<DateTimeOffset?>("MessageLastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_last_modified_at");

                    b.Property<string>("ReplyToId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reply_to_id");

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sender_display_name");

                    b.Property<string>("SenderId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sender_id");

                    b.Property<string>("Subject")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text")
                        .HasColumnName("web_url");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "ChannelId", "GraphMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_teams_messages_team_channel_graph_message");

                    b.ToTable("teams_messages", (string)null);
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.WebhookUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasMaxLength(512)
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TeamId")
                        .HasMaxLength(512)
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "ChannelId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ux_webhook_url");

                    b.ToTable("webhook_urls", (string)null);
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.MessageMedia", b =>
                {
                    b.HasOne("TeamsIntegration.Api.Entities.TeamsMessage", "TeamsMessage")
                        .WithMany("Media")
                        .HasForeignKey("TeamsMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamsMessage");
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.TeamsMessage", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
