// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamsIntegration.Api.Data;

#nullable disable

namespace TeamsIntegration.Api.Migrations
{
    [DbContext(typeof(TeamsDbContext))]
    partial class TeamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamsIntegration.Api.Entities.MessageMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("GraphAttachmentId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("graph_attachment_id");

                    b.Property<string>("GraphHostedContentId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("graph_hosted_content_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_type");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("relative_path");

                    b.Property<Guid>("TeamsMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeamsMessageId", "GraphHostedContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_message_media_hosted_content")
                        .HasFilter("\"graph_hosted_content_id\" IS NOT NULL");

                    b.ToTable("message_media", (string)null);
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.TeamsMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("channel_id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("graph_message_id");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<DateTimeOffset?>("MessageCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_created_at");

                    b.Property<DateTimeOffset?>("MessageDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_deleted_at");

                    b.Property<DateTimeOffset?>("MessageLastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_last_modified_at");

                    b.Property<string>("ReplyToId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reply_to_id");

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sender_display_name");

                    b.Property<string>("SenderId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sender_id");

                    b.Property<string>("Subject")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text")
                        .HasColumnName("web_url");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "ChannelId", "GraphMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_teams_messages_team_channel_graph_message");

                    b.ToTable("teams_messages", (string)null);
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.MessageMedia", b =>
                {
                    b.HasOne("TeamsIntegration.Api.Entities.TeamsMessage", "TeamsMessage")
                        .WithMany("Media")
                        .HasForeignKey("TeamsMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamsMessage");
                });

            modelBuilder.Entity("TeamsIntegration.Api.Entities.TeamsMessage", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
